# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- release/*

pool:
  vmImage: 'macos-latest'

steps:
- task: Bash@3
  inputs:
    filePath: 'build-universal-framework.sh'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'build'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/FanFind-iOS-$(Version).zip'
    replaceExistingArchive: true
- task: GitHubRelease@0
  inputs:
    gitHubConnection: 'stasdemir'
    repositoryName: 'Turnoutt/FanFind-iOS'
    action: 'create'
    target: '6db92d020e381b111d8fdea1712c890a4d034be7'
    tagSource: 'manual'
    tag: '$(Version)'
    title: 'FanFind-iOS $(Version)'
    releaseNotesSource: 'input'
    releaseNotes: 'None'
    addChangeLog: false

- task: Bash@3
  displayName: Build podspec
  inputs:
      targetType: inline
      script: |
        cat > FanFindTemp.podspec << EOL 
        Pod::Spec.new do |spec|
            spec.name         = "FanFind"
            spec.version      = "0.1.11"
            spec.summary      = "FanFind is a tool for helping fans find each other anonymously in real time."

            spec.description  = <<-DESC
            This cocoapods library helps you easily integrate the FanFind API in your application.
                            DESC

            spec.homepage     = "https://www.turnoutt.com"
            spec.license      = "MIT"
            spec.author             = { "Chris Woolum" => "chris@turnoutt.com" }

            spec.ios.deployment_target = "12.1"
            spec.swift_version = "4.2"

            spec.source        = { :http => "https://github.com/Turnoutt/FanFind-iOS/releases/download/0.1.11/FanFind-iOS-0.1.11.zip" }

            spec.vendored_frameworks = "build/universal/FanFindSDK.framework"
        
        end
        EOL

- task: Bash@3
  displayName: Publish podspec
  inputs:
      script: pod trunk push FanFindTemp.podspec --allow-warnings 
